name: diffusers
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy
  - matplotlib
  - opencv
  - ipykernel
  - pip
  - pip:
    - lovely-tensors
    - diffusers
    - transformers
    - accelerate
    # extra requirements for textual inversion training
    - accelerate
    - torchvision
    - transformers>=4.25.1
    - ftfy
    - tensorboard
    - Jinja2